#!/usr/bin/python

import minimalmodbus
import sys

value=['off','on']

instrument = minimalmodbus.Instrument('/dev/ttyVMC1',0)
instrument.serial.baudrate = 19200
instrument.serial.bytesize = 8
instrument.serial.parity = 'E'
instrument.serial.stopbits = 1

def read_value(address):
  while True:
    try:
      result = instrument.read_bit(address,1)
    except ValueError, IOError:
      time.sleep(1)
      continue
    break
  return result

def write_value(address,value):
  while True:
    try:
      result = instrument.write_bit(9,value)
    except ValueError, IOError:
      time.sleep(1)
      continue
    break
  return result

if len(sys.argv) == 2:
  newvalue=int(sys.argv[1])
  result = read_value(9)
  print "Current setting : ",value[result]
  if newvalue != result:
    print "Change setting to : ",value[newvalue]
    write_value(9,newvalue)
    result = read_value(9)
    print "New setting : ",value[result]
  else:
    print "Same value, nothing to do"
else:
  print "Usage : ",sys.argv[0]," <0|1>"
