#!/usr/bin/python

import minimalmodbus
import sys
from retrying import retry

value=['low','boost','bypass']

instrument = minimalmodbus.Instrument('/dev/ttyVMC1',0)
instrument.serial.baudrate = 19200
instrument.serial.bytesize = 8
instrument.serial.parity = 'E'
instrument.serial.stopbits = 1

@retry(stop_max_delay=900, wait_fixed=50)
def get_vmc_mode():
    return instrument.read_register(15,0,3,False)
    
try:
    result=get_vmc_mode()
    print('{ "airflow_mode": "%s", "airflow_readable": "%s" }'%(result,value[result]))
except ValueError as e:
    print('{ "airflow_mode": "-", "airflow_readable": "unknown", "error": "%s" }'%(e))
except TypeError as e:
    print('{ "airflow_mode": "-", "airflow_readable": "unknown", "error": "%s" }'%(e))
except IOError as e:
    print('{ "airflow_mode": "-", "airflow_readable": "unknown", "error": "%s" }'%(e))
